<?php $productCollection = $magewire->products; ?>
<div class="products wrapper grid products-grid" />
    <ol class="products list items product-items">
        <?php foreach ($productCollection as $product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $product['entity_id'] ?>"
                     data-container="product-grid">
                    <div class="product details product-item-details">
                        <strong>
                                <?=/* @noEscape */ $block->stripTags($product['name'], null, true); ?>
                        </strong>
                    </div>
                 </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
